version: '3.4'

services:
  user.sor:    
    build:
      context: .
      dockerfile: ./Dockerfile
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_sor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_TRUST_LOCALNET: 1
    ports:
    - "5436:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d